version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - gocritic
    - goconst
    - lll
    - unused
    - dupl
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
      - path: shared/model/
        linters:
          - lll

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120

run:
  timeout: 10m
  relative-path-mode: gomod
  allow-parallel-runners: true
  allow-serial-runners: true
  concurrency: 4
