services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  user:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    container_name: user-service-container
    working_dir: /app/services/user
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      - ENVIRONMENT=development
      - TERM=xterm-256color
      - COMPOSE_BAKE=true
    env_file:
      - path: .env
        required: true

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: auth-service-container
    working_dir: /app/services/auth
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
      - TERM=xterm-256color
      - COMPOSE_BAKE=true
    env_file:
      - path: .env
        required: true

volumes:
  postgres_data:
