services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  consul:
    image: hashicorp/consul:1.21
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    restart: unless-stopped

  traefik:
    image: traefik:v2.10
    container_name: traefik-container
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml

  swagger:
    build:
      context: .
      dockerfile: swagger/Dockerfile
    container_name: swagger-container
    volumes:
      - .:/app
    ports:
      - "10000:10000"

volumes:
  postgres_data:
