http:
  routers:
    user:
      rule: "Host(`go.localhost`) && PathPrefix(`/api/v1/users`)"
      service: user-service
      entryPoints:
        - web
    auth:
      rule: "Host(`go.localhost`) && PathPrefix(`/api/v1/auth`)"
      service: auth-service
      entryPoints:
        - web

  services:
    user-service:
      loadBalancer:
        servers:
          - url: "http://user:8000"
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth:8001"
